[package]
description = "Bit-banding access for STM32 peripherals"
name = "stm32-hal"
version = "0.3.0-alpha"
edition = "2021"

[dependencies]
stm32f1 = { version = "0.14.0", optional = true }
vcell = { version = "0.1.3", optional = true }

[features]
stm32f103 = ["vcell", "stm32f1/stm32f103"]
